name: Publish Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.0
          run_install: false
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.0
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build packages
        run: pnpm -r build
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Update package versions
        run: |
          find ./projects -name "package.json" -not -path "*/node_modules/*" | xargs -I{} sh -c '
            jq ".version = \"${{ steps.get_version.outputs.VERSION }}\"" {} > tmp.json && mv tmp.json {}
          '
      
      - name: Publish packages
        run: pnpm -r publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}